### ISSUE TITLE
Parameter completion

### ISSUE THREAD

**Issue by sillykelvin** [roxma/ncm-clang#4]
I see in the screenshot you have parameter completion for functions, how did you achieve that? I tried, without luck, is there any variable should be configured?

**Comment by roxma** [comment]
You need to learn to use a snippet plugin. Pick  one from Ultisnips, snipMate or neosnippet .

**Comment by sillykelvin** [comment]
I do have Ultisnips installed, I just didn't know that this feature is implemented through the snippet engine, now it works, thanks for your information and thanks for the great plugin!
