### ISSUE TITLE
Can increase the .clang_complete search path?

### ISSUE THREAD

**Issue by fcying** [roxma/ncm-clang#7]
like .ycm_extra_conf.py in YCM.

```
YCM looks for a .ycm_extra_conf.py file in the directory of the opened file or in any directory above it in the hierarchy (recursively);
```

Even better if can support system environment variables in .clang_complete

**Comment by roxma** [comment]
Have you tested the plugin?

It searches upward recursively.

**Comment by fcying** [comment]
My fault, .clang_complete was found.

I wrote the relative include path, it relative to the .clang_complete, not relative to the current file.

It can  use system environment variables  in .clang_complete? I test no work.

**Comment by roxma** [comment]
Just pushed an update

Please test it

**Comment by fcying** [comment]
it can work, thanks~~
